version: "3.9"

services:
    database:
        #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
        image: mariadb:10.7.1
        container_name: dabase
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=database
        volumes:
            - mdbdata:/data/mariadb

    app:
        build: .
        container_name: backend
        restart: always
        ports:
            - 3333:3333
            - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    mdbdata:
        driver: local
